clhero:
  # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

  # Position Controllers ---------------------------------------
    motor1_position_controller:
        type: effort_controllers/JointPositionController
        joint: motor_1_to_base_link_joint
        pid: {p: 20, i: 10, d: 0.5}
    motor2_position_controller:
        type: effort_controllers/JointPositionController
        joint: motor_2_to_base_link_joint
        pid: {p: 20, i: 10, d: 0.5}
    motor3_position_controller:
        type: effort_controllers/JointPositionController
        joint: motor_3_to_base_link_joint
        pid: {p: 20, i: 10, d: 0.5}
    motor4_position_controller:
        type: effort_controllers/JointPositionController
        joint: motor_4_to_base_link_joint
        pid: {p: 20, i: 10, d: 0.5}
    motor5_position_controller:
        type: effort_controllers/JointPositionController
        joint: motor_5_to_base_link_joint
        pid: {p: 20, i: 10, d: 0.5}
    motor6_position_controller:
        type: effort_controllers/JointPositionController
        joint: motor_6_to_base_link_joint
        pid: {p: 20, i: 10, d: 0.5}

  # Velocity Controllers ---------------------------------------
    motor1_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: motor_1_to_base_link_joint
        pid: {p: 2, i: 10, d: 0}
    motor2_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: motor_2_to_base_link_joint
        pid: {p: 2, i: 10, d: 0}
    motor3_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: motor_3_to_base_link_joint
        pid: {p: 2, i: 10, d: 0}
    motor4_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: motor_4_to_base_link_joint
        pid: {p: 2, i: 10, d: 0}
    motor5_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: motor_5_to_base_link_joint
        pid: {p: 2, i: 10, d: 0}
    motor6_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: motor_6_to_base_link_joint
        pid: {p: 2, i: 10, d: 0}

